# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-31 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to='groups/')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
